### ISSUE TITLE
checksum: calculating a save's checksum

### ISSUE THREAD

**Issue by gucio321** [gucio321/d2d2s#1]
the save files has to contain a 32-bit checksum, because the game will not read them.
## what do we know about this field?
- [documentation](https://user.xmission.com/~trevin/DiabloIIv1.09_File_Format.shtml)
![image](https://user-images.githubusercontent.com/73652197/117999258-f38a3080-b344-11eb-81d9-dd106db9ff97.png)

checksum needs to be calculated in the same way as `file size`.

**Comment by gucio321** [comment]
looks, like the game doesn't read a files only because of this issue.

**Comment by gucio321** [comment]
also, the code actually calculates a checksum [here](https://github.com/gucio321/d2d2s/blob/4c0ea38179994eaf9711abb6b75cda0c89c67129/d2s.go#L379) but sadly in a wrong way :cry: 
[here](https://github.com/krisives/d2s-format#checksum) is also a checksum description

**Comment by pairofdocs** [comment]
thrugg_aka_trogg on discord

I also used https://github.com/krisives/d2s-format#checksum as a reference

the way I did the checksum calc was 
https://github.com/pairofdocs/d2s_edit_recalc/blob/master/edit_and_recalc.py#L11-L18

so I think if you set the four bytes of `data[i]` where the checksum is placed to `00`s that calculation should work
`data[12:16] = 0`

**Comment by gucio321** [comment]
@pairofdocs thanks for link to your repo. I'll take a look.

I think, that I'm doing something wrong, because my checksum isn't equal to base sum but data are.
The game doesn't want to read my saves.
![image](https://user-images.githubusercontent.com/73652197/118616256-d11f6980-b7c1-11eb-8a61-01a1efe5e91f.png)

**Comment by gucio321** [comment]
@pairofdocs I fixed it with your code! thanx a lot!
the problem was, that `sum <<= 1` wasn't correct. this expression should look like:
```golang
                sum = ((sum << 1) % math.MaxUint32) | (sum >> (int32Size*byteLen - 1))
```
